# Generated by Django 2.2.12 on 2020-09-28 09:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanierEnCours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.IntegerField()),
                ('donnees', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
